### ISSUE TITLE
 Cannot find namespace 'DataTables' 

### ISSUE THREAD

**Issue by harshavarun25** [l-lin/angular-datatables#1248]
I have imported everything right as per the documentation.
I still get the error CANNOT FIND NAMESPACE  DATATABLES.

```
"@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@ngx-translate/core": "^10.0.1",
    "angular-datatables": "^6.0.0",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.6",
    "datatables.net": "^1.10.16",
    "datatables.net-dt": "^1.10.16",
    "jquery": "^3.3.1",
```
If you can help me it would be great.
Thank you.
@l-lin

**Comment by l-lin** [comment]
Did you import the `DataTablesModule` into your app?

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { DataTablesModule } from 'angular-datatables';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,

    DataTablesModule
  ],
  providers: [],
  bootstrap: [ AppComponent ]
})
export class AppModule {}
```

**Comment by Killerbear** [comment]
i followed the instructions in the doc and import the `DataTablesModule` into my app and get the same error:

```
ERROR in node_modules/angular-datatables/src/angular-datatables.directive.d.ts(1,23): error TS2688: Cannot find type definition file for 'datatables.net'.
node_modules/angular-datatables/src/angular-datatables.directive.d.ts(15,16): error TS2503: Cannot find namespace 'DataTables'.
node_modules/angular-datatables/src/angular-datatables.directive.d.ts(27,25): error TS2503: Cannot find namespace 'DataTables'.
```

**Comment by vijay1989** [comment]
ERROR in node_modules/angular-datatables/src/angular-datatables.directive.d.ts(1,23): error TS2688: Cannot find
node_modules/angular-datatables/src/angular-datatables.directive.d.ts(15,16): error TS2503: Cannot find namespace 'DataTables'.

**Comment by Killerbear** [comment]
What solved and closed?
No. Nothing has changed.

As we

**Comment by Killerbear** [comment]
What?
solved and closed?
No. Nothing has changed.

As harshavarun25 and me mentioned: we followed the install instructions exactly.
This means, we installed every dependencys from npm added styles and scripts to angular.json and imported the module into app.modules.ts.

you can simply recreate this.
ng new app
follow your datatable install instructions
and try to serve

-> Errors will occur

**Comment by Killerbear** [comment]
Okay i know why i´m getting this error.
I used the atom console to install the npm packages.
But with this methode i got these errors.

When i use gitbash to install the npm dependencies, everything works fine

**Comment by navneett76** [comment]
We have again install using command "npm i @types/datatables.net --save-dev" through cmd but still getting the same issue. 

Error: can not found namespace datatables

I am also using the latest CLI "6.1.5" and Angular "6.1.4"

**Comment by jmedinac1987** [comment]
To solve this error they must change in the package.json the dependency: "angular-datatables": "^ 0.6.3", by "angular-datatables": "^ 6.0.0".

After refreshing the package.json with the command npm install.

Note: sorry for my level of English

**Comment by andersonst** [comment]
import "datatables.net";

**Comment by nicogaldo** [comment]
I have the same problem with angular-datatables version 7.0.0 with Angular 6
Fixed downgrade version of angular-datables to 6.0.0

`npm uninstall angular-datatables`
`npm install angular-datatables@6.0.0`

**Comment by dawand** [comment]
I added the following to the `devDependencies` in `package.json`:
```
"@types/datatables.net": "^1.10.8"
```

**Comment by sajeebchandan** [comment]
> solved, `npm i @types/datatables.net --save-dev`

Thanks a lot man. It really worked

**Comment by umeshbichukale** [comment]
After Installing  `npm install angular-datatables@latest ` it got resolved

**Comment by sighdok** [comment]
Hello everyone. 
Not sure if I should open a new issue - this problem still persists on my environment I would really appreciate any help. I've tried all solutions from this thread as well as many more from the google search but I can't serve my angular application. 
I've also followed the installation instructions many times, cleaned the npm cache and so on... 
Can anyone help me? Do you need more informations? I use the latest version of angular-datatables and angular 17

**Comment by Ponusiva** [comment]
> Hello everyone.
> 
> Not sure if I should open a new issue - this problem still persists on my environment I would really appreciate any help. I've tried all solutions from this thread as well as many more from the google search but I can't serve my angular application. I've also followed the installation instructions many times, cleaned the npm cache and so on... Can anyone help me? Do you need more informations? I use the latest version of angular-datatables and angular 17
> 
> @l-lin maybe?

Even I too faced issue after angular 14 + upgrade but this really solved the problem, npm i @types/datatables.net --save-dev

**Comment by sighdok** [comment]
@Ponusiva no, unfortunately this doesn't work... huge project is one break caused by this problem :/ Can you tell me which version of @types/datatables.net you have in your package.json? Thanks in advance

**Comment by AntoineBrunelle** [comment]
> @Ponusiva no, unfortunately this doesn't work... huge project is one break caused by this problem :/ Can you tell me which version of @types/datatables.net you have in your package.json? Thanks in advance

Have you found a solution ? I'm facing the same issue, and I can't find any solution

**Comment by TungDao1102** [comment]
@AntoineBrunelle i have same problem :(

**Comment by AntoineBrunelle** [comment]
@TungDao1102 And the solution I wrote in my "EDIT" doesn't work in your case ?

**Comment by TungDao1102** [comment]
@AntoineBrunelle no sir, here is my code `import { AfterViewInit, Component, ElementRef, QueryList, ViewChild, ViewChildren } from '@angular/core';
import { BreadcrumbComponent } from '../../../../shared/components/breadcrumb/breadcrumb.component';
import { DataTablesModule } from 'angular-datatables';
import DataTables from "datatables.net";
import { Settings } from '@types/datatables.net';

@Component({
  selector: 'app-create',
  standalone: true,
  imports: [BreadcrumbComponent, DataTablesModule],
  templateUrl: './create.component.html',
  styleUrl: './create.component.css'
})
export class CreateComponent implements AfterViewInit {
  dtOptions: DataTables.Settings = {};
  `
  'Settings' is declared but its value is never read.ts(6133)
Cannot find module '@types/datatables.net' or its corresponding type declarations.ts(2307)
Cannot import type declaration files. Consider importing 'datatables.net' instead of '@types/datatables.net'
'DataTables' only refers to a type, but is being used as a namespace here

**Comment by triumlabs** [comment]
I was facing the same issue.
What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. 
In my case it was: "@types/datatables.net": "~1.10.21"
Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!

Hope it helps.

**Comment by TungDao1102** [comment]
@triumlabs thanks bro. it worked

**Comment by EngineerIT14** [comment]
> I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> 
> Hope it helps.

It works, thanks hero!

**Comment by Krishnapro** [comment]
> I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> 
> Hope it helps.

It's work, Thank for the solution.

**Comment by lariloran** [comment]
> I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> 
> Hope it helps.

It'work, man! Thanks a lot. 

God bless u all!

**Comment by anarbek** [comment]
This worked for me:
npm install @types/datatables.net@1.10.21 --save-dev

**Comment by romansad** [comment]
I have Datatables 14.0.2 and with  npm install @types/datatables.net@1.10.21 --save-dev   recompile project and works fine for me 

Tks!!

**Comment by vijayavarmank** [comment]
This is working

**Comment by codezilla91** [comment]
> I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> 
> Hope it helps.

It's 2024, i spent a few days on this issue and the solution above worked for me. It's not enough to simply run: npm install @types/datatables.net@1.10.21 --save-dev

Your package.json file needs to read as: "@types/datatables.net": "~1.10.21", and not "@types/datatables.net": "^1.10.21",

take note of  (^1.10.21) vs  (~1.10.21)

**Comment by delarco** [comment]
> > I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> > Hope it helps.
> 
> It's 2024, i spent a few days on this issue and the solution above worked for me. It's not enough to simply run: npm install @types/datatables.net@1.10.21 --save-dev
> 
> Your package.json file needs to read as: "@types/datatables.net": "~1.10.21", and not "@types/datatables.net": "^1.10.21",
> 
> take note of (^1.10.21) vs (~1.10.21)

this solved for me! tyvm!

**Comment by JoeMeeks** [comment]
> I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> 
> Hope it helps.

Also with `"angular-datatables": "17.0.0"` I had to do the following to ensure compilation:
```npm i @types/datatables.net@1.10.21 -D -E```

**Comment by souravr186** [comment]
> I was facing the same issue. What worked for me is install exactly the same version of @types/datatables.net as it is declared in node_modules\angular-datatables\package.json. In my case it was: "@types/datatables.net": "~1.10.21" Note that even declaring ^1.10.21 did not work, only as ~1.10.21 !!
> 
> Hope it helps.

Thank you so much!
for version angular-datatables version 17.1.0 same "npm i @types/datatables.net@1.10.21 --save" worked

**Comment by alonsofritz** [comment]
> > @Ponusivanão, infelizmente isso não funciona... projeto enorme é uma quebra causada por esse problema :/ Você pode me dizer qual versão de @types/datatables.net você tem em seu package.json? desde já, obrigado
> 
> Você encontrou uma solução ? Estou enfrentando o mesmo problema e não consigo encontrar nenhuma solução
> 
> - EDIT: No meu caso não funcionou porque a biblioteca "@types/datatables.net" agora está obsoleta. Eles removeram o arquivo de declaração na versão 1.12.0. Forcei a instalação da versão 1.10.16, ao invés de `@types/datatables.net: ^1.10.16`agora tenho`@types/datatables.net: 1.10.16`

somente essa abordagem funcionou aqui, realmente deve ser relacionado a remoção do arquivo de declaração na versão 1.12.0. 
Obrigado.
